name: TCGA-OV 
channels:
  - conda-forge
  - base
  - R
  - bioconda
dependencies:
  - snakemake
  - r-base=4.3.1
  - r-tidyverse=2.0.0
  - r-caret=6.0_94
  - r-glmnet=4.1_7
  - r-rockchalk=1.8.157
  - r-gplots=3.1.3
  - r-WGCNA=1.71
  - r-gridExtra=2.3
  - r-venn=1.11 
  - bioconductor-TCGAbiolinks=2.28.3
  - bioconductor-SummarizedExperiment=1.30.2 
  - bioconductor-ComplexHeatmap=2.16.0
  - bioconductor-DESeq2=1.40.2 
  - bioconductor-biomaRt=2.56.1 
  - bioconductor-topGO=2.52.0
  - bioconductor-phantasus=1.20.2
  - bioconductor-GDCRNATools=1.20.0
  - r-UCSCXenaTools
  - r-dendextend
#corlevelplot is not in conda


