name: TCGA-OV 
channels:
  - conda-forge
  - base
  - R
  - bioconda
dependencies:
  - snakemake
  - r-base=4.3.1
  - r-tidyverse=2.0.0
  - r-caret=6.0_94
  - r-glmnet=4.1_7
  - r-rockchalk=1.8.157
  - r-gplots=3.1.3
  - r-WGCNA
  - r-gridExtra
  - r-venn
  - bioconductor-TCGAbiolinks=2.28.3
  - bioconductor-SummarizedExperiment=1.30.2 
  - bioconductor-ComplexHeatmap=2.16.0
  - bioconductor-DESeq2
  - bioconductor-biomaRt
#corlevelplot is not in conda


